zuul:
  routes:
    auth:
      path: /auth/**
      url: ${SSO_ADDRESS}/realms/blog/protocol/openid-connect/token
      sensitiveHeaders:
  add-proxy-headers: false
  ignored-headers: Host,X-Forwarded-Host

logging.level:
  org.springframework: DEBUG
  org.hibernate: DEBUG
  org.keycloak: TRACE

spring:
  mvc:
    log-request-details: true
  application:
    name: auth-gateway

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}